[core]
idle-time=0
shell=desktop-shell.so

[shell]
# Rotate the display (options: 0, 90, 180, 270)
transform=90

[output]
name=HDMI-A-1
mode=1920x1080
transform=90

[input-method]
path=/usr/libexec/weston-keyboard

[touch-calibration]
device=/dev/input/event0
calibration=0 1 0 1 0 0

